namespace ExcelCore.Model
{
    public class LocalizeCharProfile
    {
        public long CharacterId { get; set; }
        public string StatusMessageKr { get; set; }
        public string StatusMessageJp { get; set; }
        public string StatusMessageTh { get; set; }
        public string StatusMessageTw { get; set; }
        public string StatusMessageEn { get; set; }
        public string FullNameKr { get; set; }
        public string FullNameJp { get; set; }
        public string FullNameTh { get; set; }
        public string FullNameTw { get; set; }
        public string FullNameEn { get; set; }
        public string FamilyNameKr { get; set; }
        public string FamilyNameRubyKr { get; set; }
        public string PersonalNameKr { get; set; }
        public string PersonalNameRubyKr { get; set; }
        public string FamilyNameJp { get; set; }
        public string FamilyNameRubyJp { get; set; }
        public string PersonalNameJp { get; set; }
        public string PersonalNameRubyJp { get; set; }
        public string FamilyNameTh { get; set; }
        public string FamilyNameRubyTh { get; set; }
        public string PersonalNameTh { get; set; }
        public string PersonalNameRubyTh { get; set; }
        public string FamilyNameTw { get; set; }
        public string FamilyNameRubyTw { get; set; }
        public string PersonalNameTw { get; set; }
        public string PersonalNameRubyTw { get; set; }
        public string FamilyNameEn { get; set; }
        public string FamilyNameRubyEn { get; set; }
        public string PersonalNameEn { get; set; }
        public string PersonalNameRubyEn { get; set; }
        public string SchoolYearKr { get; set; }
        public string SchoolYearJp { get; set; }
        public string SchoolYearTh { get; set; }
        public string SchoolYearTw { get; set; }
        public string SchoolYearEn { get; set; }
        public string CharacterAgeKr { get; set; }
        public string CharacterAgeJp { get; set; }
        public string CharacterAgeTh { get; set; }
        public string CharacterAgeTw { get; set; }
        public string CharacterAgeEn { get; set; }
        public string BirthDay { get; set; }
        public string BirthdayKr { get; set; }
        public string BirthdayJp { get; set; }
        public string BirthdayTh { get; set; }
        public string BirthdayTw { get; set; }
        public string BirthdayEn { get; set; }
        public string CharHeightKr { get; set; }
        public string CharHeightJp { get; set; }
        public string CharHeightTh { get; set; }
        public string CharHeightTw { get; set; }
        public string CharHeightEn { get; set; }
        public string DesignerNameKr { get; set; }
        public string DesignerNameJp { get; set; }
        public string DesignerNameTh { get; set; }
        public string DesignerNameTw { get; set; }
        public string DesignerNameEn { get; set; }
        public string IllustratorNameKr { get; set; }
        public string IllustratorNameJp { get; set; }
        public string IllustratorNameTh { get; set; }
        public string IllustratorNameTw { get; set; }
        public string IllustratorNameEn { get; set; }
        public string CharacterVoiceKr { get; set; }
        public string CharacterVoiceJp { get; set; }
        public string CharacterVoiceTh { get; set; }
        public string CharacterVoiceTw { get; set; }
        public string CharacterVoiceEn { get; set; }
        public string KRCharacterVoiceKr { get; set; }
        public string KRCharacterVoiceTh { get; set; }
        public string KRCharacterVoiceTw { get; set; }
        public string KRCharacterVoiceEn { get; set; }
        public string HobbyKr { get; set; }
        public string HobbyJp { get; set; }
        public string HobbyTh { get; set; }
        public string HobbyTw { get; set; }
        public string HobbyEn { get; set; }
        public string WeaponNameKr { get; set; }
        public string WeaponDescKr { get; set; }
        public string WeaponNameJp { get; set; }
        public string WeaponDescJp { get; set; }
        public string WeaponNameTh { get; set; }
        public string WeaponDescTh { get; set; }
        public string WeaponNameTw { get; set; }
        public string WeaponDescTw { get; set; }
        public string WeaponNameEn { get; set; }
        public string WeaponDescEn { get; set; }
        public string ProfileIntroductionKr { get; set; }
        public string ProfileIntroductionJp { get; set; }
        public string ProfileIntroductionTh { get; set; }
        public string ProfileIntroductionTw { get; set; }
        public string ProfileIntroductionEn { get; set; }
        public string CharacterSSRNewKr { get; set; }
        public string CharacterSSRNewJp { get; set; }
        public string CharacterSSRNewTh { get; set; }
        public string CharacterSSRNewTw { get; set; }
        public string CharacterSSRNewEn { get; set; }
    }
}
